server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/enrollments/**

        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/exams/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
